# Generated by Django 5.1.6 on 2025-02-26 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culinaryweb.service'),
            preserve_default=False,
        ),
    ]
