# Generated by Django 5.1.3 on 2025-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candydescription',
            name='flavor',
            field=models.CharField(max_length=255),
        ),
    ]
