# Generated by Django 5.1.3 on 2025-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_alter_candydescription_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='candydescription',
            name='colors',
            field=models.ManyToManyField(related_name='candies', to='candy.color'),
        ),
    ]
